class ModbusRtuFCodes:
    READ_COILS = 0x1
    READ_DISCRETE_INPUTS = 0x2
    READ_HOLDING_REGISTERS = 0x3
    WRITE_SINGLE_COIL = 0x5
    WRITE_SINGLE_REGISTER = 0x6
    WRITE_MULTIPLE_COILS = 0xF
    WRITE_MULTIPLE_REGISTERS = 0x10

class ModbusRtuExceptions:
    ILLEGAL_FUNCTION = 0x01
    ILLEGAL_DATA_ADDRESS = 0x02
    ILLEGAL_DATA_VALUE = 0x03
    SERVER_DEVICE_FAILURE = 0x04